### ISSUE TITLE
Wrap Arrow token deployment in an upgradeable proxy

### ISSUE THREAD

**Issue by bghughes** [Arrow-air/Arrow-Contracts#10]
The Arrow ERC-20 should be wrapped in an upgradeable proxy to allow for easy future development without needing to change the coin's deployed address or have a token migration.

I am familiar with the `TransparentUpgradeableProxy` standard from OpenZeppelin which we could use here though after reading their v4 docs they are suggesting a different approach. I'd like to study this a bit more first, and then implement this into the deployment script added in #9

**Comment by GoodluckH** [comment]
@bghughes I'm actually working on this #12.
