### ISSUE TITLE
Initial token supply amount

### ISSUE THREAD

**Issue by GoodluckH** [Arrow-air/Arrow-Contracts#11]
We need to discuss and decide the initial amount of token to be minted.

**Comment by thomasgarrison** [comment]
The convention for many startups is 10,000,000 shares. While somewhat arbitrary, I think this would be a good place for us to start with our token mint. Of course, we won't allocate the majority of these on day one.

**Comment by GoodluckH** [comment]
100,000,000 
As per discussion on Discord.
