### ISSUE TITLE
Add vesting contracts for token distribution

### ISSUE THREAD

**Issue by BrassLion** [Arrow-air/Arrow-Contracts#4]
In order to reward stakeholders of the project with ARROW tokens and to prevent speculation in the short term, we should add a method of vesting tokens to beneficiaries over time.

A good base contract for implementing this is [OpenZeppelin's `VestingWallet`](https://docs.openzeppelin.com/contracts/4.x/api/finance#VestingWallet), which will lock ETH and any ERC20 tokens sent for a cliff period, then release the locked tokens over time linearly.

**Comment by BrassLion** [comment]
I've done some experiments with creating a contract factory that constructs a new `VestingWallet` for every beneficiary and sends an arbitrary number of tokens to it, which could be called when needed by the multisig in order to give tokens to new holders.

This works, but it's very gas intensive. It's about 650 000 gas to deploy a new `VestingWallet` naively, which is going to quickly make it unviable to distribute small amounts of tokens to people on L1.

I've done some work adapting the wallet to make transactions cheaper, by deploying a single contract that keeps a mapping of all beneficiaries and amounts. This looks like it'll reduce the gas cost for creating a new vesting schedule to about 100 000.

Some thoughts that have come up during this:

- Do we want the contracts to handle vesting of any arbitrary ERC20 token and ETH? Or just the Arrow token? Adding support for any token will cause gas to go up a bit, but shouldn't be too hard.
- Do we want to be doing this on an L2 in order to support smaller token distributions?
- Do we want to go another direction entirely?

@thomasgarrison @bghughes would appreciate your thoughts on this.

**Comment by thomasgarrison** [comment]
Thanks for thinking through this

> Do we want the contracts to handle vesting of any arbitrary ERC20 token and ETH? Or just the Arrow token? Adding support for any token will cause gas to go up a bit, but shouldn't be too hard.

I think that just the Arrow token will be fine. When we're paying in cash, we can just send it directly.

> Do we want to be doing this on an L2 in order to support smaller token distributions?

I'd say so. We could also make this something that the beneficiary decides depending on their preferences. There's a good chance that we'll want to switch L2s sometime in the future if we pick one today, but I think that's fine.

**Comment by bghughes** [comment]
> I've done some experiments with creating a contract factory that constructs a new `VestingWallet` for every beneficiary and sends an arbitrary number of tokens to it, which could be called when needed by the multisig in order to give tokens to new holders.
> 
> This works, but it's very gas intensive. It's about 650 000 gas to deploy a new `VestingWallet` naively, which is going to quickly make it unviable to distribute small amounts of tokens to people on L1.
> 
> I've done some work adapting the wallet to make transactions cheaper, by deploying a single contract that keeps a mapping of all beneficiaries and amounts. This looks like it'll reduce the gas cost for creating a new vesting schedule to about 100 000.
> 
> Some thoughts that have come up during this:
> 
> * Do we want the contracts to handle vesting of any arbitrary ERC20 token and ETH? Or just the Arrow token? Adding support for any token will cause gas to go up a bit, but shouldn't be too hard.
> * Do we want to be doing this on an L2 in order to support smaller token distributions?
> * Do we want to go another direction entirely?
> 
> @thomasgarrison @bghughes would appreciate your thoughts on this.

Nice work @BrassLion ! I'd love to check out the vesting mappings and think I could provide a helpful review. I only have experience deploying the vesting contracts as needed from an EOA but think this sort of approach would be great. Moreover, I believe any arbitrary ERC-20 would be the way to go for the sake of future-proofing and keeping the logic as minimal as possible.

Looking forward to checking this out!
