### ISSUE TITLE
Add hardhat implementation to smart contracts for improved ecosystem composability

### ISSUE THREAD

**Issue by bghughes** [Arrow-air/Arrow-Contracts#8]
I believe to prepare for the long-term, Arrow should adopt Hardhat as its main EVM development environment. Hardhat offers a number of advantages over Brownie in my mind that all stem from the higher level of adoption the tooling has. For instance, Hardhat has a lot of plugins that make it very easy to test, ship, and maintain a protocol deployment. My personal favorite is [`hardhat-deploy`](https://github.com/Zalkota/hardhat-deploy) and I know that many (if not all L2s) are aligning with hardhat over other options. Projects that come to mind are Optimism: for some time the only plugin that made their custom compiler usable was hardhat and they invested their resources there first over other options given its adoption. Lastly, hardhat and javascript allow for the use of Typescript in the codebase which has many natural synergies with Web3 development and may offer implicit advantages over a Python approach.

Importantly, this is no sleight on Brownie. It seems to be working well and please note the bias that I have not worked with Brownie. 

Please see here for the [Hardhat](https://hardhat.org) website and a list of [plugins here](https://hardhat.org/plugins/).

[Brownie Github](https://github.com/eth-brownie/brownie) vs. [Hardhat Github](https://github.com/NomicFoundation/hardhat)

**Comment by bghughes** [comment]
Hey, @thomasgarrison if you think it's meaningful I can pick up this ticket and implement Hardhat for base-level functionality.  

The key areas that would need work after that would be a testing suite, deployment scripts, and verification scripts.

**Comment by GoodluckH** [comment]
@bghughes  I totally agree with you on migrating to a hardhat/js driven codebase. It seems like you have already started working on this, so I will work on some smart contracts. Let me know if you need any help.
